#!/bin/sh

# Ok, this is maybe not the nicest way of doing it, but how the h*ll am I supposed to do it right?

if [ ! -f config.install-path ]; then
	echo "export CHAOS_INSTALL_PATH=$(pwd)/root" > config.install-path
fi

. config.install-path
make build
unset CHAOS_INSTALL_PATH
