#define SUBSYSTEM_SYSTEM_DEBUG
#define SUBSYSTEM_CPU
#define SUBSYSTEM_EXCEPTION
#define SUBSYSTEM_PHYSICAL_MEMORY
#define SUBSYSTEM_VIRTUAL_MEMORY
#define SUBSYSTEM_GLOBAL_MEMORY
//#define SUBSYSTEM_USER_MEMORY
#define SUBSYSTEM_MEMORY

#define SUBSYSTEM_IO_PORT
#define SUBSYSTEM_DMA
#define SUBSYSTEM_IRQ
#define SUBSYSTEM_CLOCK
#define SUBSYSTEM_TIMER

#define SUBSYSTEM_THREAD
#define SUBSYSTEM_SYSTEM_CALL
#define SUBSYSTEM_PROCESS

//#define SUBSYSTEM_REGISTER

//#define SUBSYSTEM_POSIX
//#define SUBSYSTEM_PROGRAM
//#define PROGRAM_NAME "bash"

#define SUBSYSTEM_REPOSITORY

