/* sysdefs.h -- #defines for your system created by ./support/mksysdefs.
   Do NOT EDIT this file, since any changes will disappear.
   Instead, edit ./support/mksysdefs, or config.h, or machines.h. */

#if !defined (_SYSDEFS_H_)
#  define _SYSDEFS_H_

#if !defined (RANLIB_LOCATION)
#  define RANLIB_LOCATION ranlib
#endif /* RANLIB_LOCATION */

#if !defined (SCO)
#  define SCO
#endif /* SCO */

#if !defined (HAVE_WAIT_H)
#  define HAVE_WAIT_H
#endif /* HAVE_WAIT_H */

#if !defined (HAVE_RESOURCE)
#  define HAVE_RESOURCE
#endif /* HAVE_RESOURCE */

#if !defined (HAVE_SYS_PARAM)
#  define HAVE_SYS_PARAM
#endif /* HAVE_SYS_PARAM */

#if !defined (HAVE_UNISTD_H)
#  define HAVE_UNISTD_H
#endif /* HAVE_UNISTD_H */

#if !defined (HAVE_STDLIB_H)
#  define HAVE_STDLIB_H
#endif /* HAVE_STDLIB_H */

#if !defined (HAVE_LIMITS_H)
#  define HAVE_LIMITS_H
#endif /* HAVE_LIMITS_H */

#if !defined (HAVE_ALLOCA_H)
#  define HAVE_ALLOCA_H
#endif /* HAVE_ALLOCA_H */

#if !defined (HAVE_DIRENT_H)
#  define HAVE_DIRENT_H
#endif /* HAVE_DIRENT_H */

#if !defined (HAVE_STRING_H)
#  define HAVE_STRING_H
#endif /* HAVE_STRING_H */

#if !defined (HAVE_DEV_FD)
#  define HAVE_DEV_FD
#endif /* HAVE_DEV_FD */

#if !defined (HAVE_BISON)
#  define HAVE_BISON
#endif /* HAVE_BISON */

#endif /* _SYSDEFS_H_ */
