
enum
{
  VFAT_RETURN_SUCCESS,
  VFAT_RETURN_UNSUCCESSFULL,
  VFAT_RETURN_NO_MORE_ENTRIES,
  VFAT_RETURN_UNRECOGNIZED_VOLUME,
  VFAT_RETURN_DISK_FULL,
  VFAT_RETURN_IO_ERROR,
  VFAT_RETURN_NO_MEMORY,
  VFAT_RETURN_NAME_NOT_FOUND,
  VFAT_RETURN_PATH_NOT_FOUND,
  VFAT_RETURN_NAME_INVALID,
  VFAT_RETURN_END_OF_FILE,
  VFAT_RETURN_FILE_NOT_OPENED,
};
