#define SUBSYSTEM_SYSTEM_DEBUG
#define SUBSYSTEM_CPU
#define SUBSYSTEM_EXCEPTION
#define SUBSYSTEM_PHYSICAL_MEMORY
#define SUBSYSTEM_VIRTUAL_MEMORY
#define SUBSYSTEM_IO_PORT
#define SUBSYSTEM_DMA
#define SUBSYSTEM_IRQ
#define SUBSYSTEM_CLOCK
#define SUBSYSTEM_TIMER
#define SUBSYSTEM_TASK_STATE
#define SUBSYSTEM_ELF
#define SUBSYSTEM_SYSTEM_CALL

#define SUBSYSTEM_REPOSITORY


