# $Id: makefile.template,v 1.2 2001/02/10 21:26:00 jojo Exp $
# Local rules

wrapper.c system_calls-auto.c: system_calls.pl
	@./system_calls.pl

DEFINES="-DCREATOR=\"`whoami`@`hostname`\""
EXTRA_FILES=system_calls.pl kernel.ld