# $Id: makefile.template,v 1.3 2001/03/10 11:34:17 jojo Exp $
# Local rules.

storm: current-arch

# FIXME: Make this detect the architecture in some way.

current-arch:
	ln -sf ia32 current-arch
	ln -sf ia32 include/storm/current-arch

clean-local:
	rm -f current-arch
