# $Id: makefile.template,v 1.1.1.1 2000/09/26 19:08:16 plundis Exp $
# Local rules.

storm: current-arch

# FIXME: Make this detect the architecture in some way.

current-arch:
	ln -sf ia32 current-arch

clean-local:
	rm -f current-arch
