/* Generated automatically by system_calls.pl */

#ifndef __STORM_SYSTEM_CALLS_H__
#define __STORM_SYSTEM_CALLS_H__

#define SYSTEM_CALLS 42

enum
{
  SYSTEM_CALL_INIT = 48,
  SYSTEM_CALL_KERNELFS_ENTRY_READ,
  SYSTEM_CALL_MAILBOX_CREATE,
  SYSTEM_CALL_MAILBOX_DESTROY,
  SYSTEM_CALL_MAILBOX_FLUSH,
  SYSTEM_CALL_MAILBOX_SEND,
  SYSTEM_CALL_MAILBOX_RECEIVE,
  SYSTEM_CALL_SERVICE_CREATE,
  SYSTEM_CALL_SERVICE_DESTROY,
  SYSTEM_CALL_SERVICE_GET,
  SYSTEM_CALL_SERVICE_PROTOCOL_GET,
  SYSTEM_CALL_SERVICE_PROTOCOL_GET_AMOUNT,
  SYSTEM_CALL_DMA_TRANSFER,
  SYSTEM_CALL_DMA_TRANSFER_CANCEL,
  SYSTEM_CALL_DMA_REGISTER,
  SYSTEM_CALL_DMA_UNREGISTER,
  SYSTEM_CALL_IRQ_REGISTER,
  SYSTEM_CALL_IRQ_UNREGISTER,
  SYSTEM_CALL_IRQ_WAIT,
  SYSTEM_CALL_IRQ_ACKNOWLEDGE,
  SYSTEM_CALL_MEMORY_ALLOCATE,
  SYSTEM_CALL_MEMORY_DEALLOCATE,
  SYSTEM_CALL_MEMORY_RESERVE,
  SYSTEM_CALL_MEMORY_GET_PHYSICAL_ADDRESS,
  SYSTEM_CALL_PORT_RANGE_REGISTER,
  SYSTEM_CALL_PORT_RANGE_UNREGISTER,
  SYSTEM_CALL_PROCESS_CREATE,
  SYSTEM_CALL_PROCESS_NAME_SET,
  SYSTEM_CALL_PROCESS_PARENT_UNBLOCK,
  SYSTEM_CALL_THREAD_CREATE,
  SYSTEM_CALL_THREAD_CONTROL,
  SYSTEM_CALL_THREAD_NAME_SET,
  SYSTEM_CALL_TIMER_READ,
  SYSTEM_CALL_DISPATCH_NEXT,
  SYSTEM_CALL_EVENT_QUEUE_CREATE,
  SYSTEM_CALL_EVENT_QUEUE_DESTROY,
  SYSTEM_CALL_EVENT_QUEUE_FLUSH,
  SYSTEM_CALL_EVENT_QUEUE_GET_INFO,
  SYSTEM_CALL_EVENT_QUEUE_REGISTER_LISTENER,
  SYSTEM_CALL_EVENT_QUEUE_UNREGISTER_LISTENER,
  SYSTEM_CALL_EVENT_QUEUE_GENERATE_EVENT,
  SYSTEM_CALL_EVENT_QUEUE_WAIT_EVENT,
};

#endif /* !__STORM_SYSTEM_CALL_H__ */
