# $chaos: makefile.template,v 1.1 2002/05/25 20:08:27 per Exp $

# Abstract: storm G3 makefile
# Authors: Henrik Hallin <hal@chaosdev.org>
#          Per Lundberg <per@chaosdev.org>

# Copyright 2002 chaos development.

# INSERT CODE HERE.

include $(BUILDROOT)/storm.make
