/* ATTENTION! THIS FILE GENERATED BY IDL2C, DO NOT EDIT! */

#ifndef __INTERFACE_BLOCK_H__
#define __INTERFACE_BLOCK_H__

#include "interface_ids.h"

enum
{
};



typedef struct
{
} interface_block_t;

#endif /* !__INTERFACE_BLOCK_H__ */

