/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
static yyconst short int yy_acclist[398] =
    {   0,
       61,   61,   64,   62,   63,   61,   62,   63,   61,   63,
       62,   63,   62,   63,   52,   62,   63,   56,   62,   63,
       54,   62,   63,   62,   63,   62,   63,   62,   63,   51,
       62,   63,   51,   62,   63,   51,   62,   63,   51,   62,
       63,   51,   62,   63,   51,   62,   63,   51,   62,   63,
       51,   62,   63,   51,   62,   63,   51,   62,   63,   51,
       62,   63,   51,   62,   63,   51,   62,   63,   51,   62,
       63,   51,   62,   63,   51,   62,   63,   51,   62,   63,
       51,   62,   63,   51,   62,   63,   51,   62,   63,   51,
       62,   63,   51,   62,   63,   51,   62,   63,   61,   57,

       52,   52,   52,   56,   54,   50,   48,   49,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   18,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   58,   52,   53,   55,   51,   51,   51,   51,
       51,    2,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   27,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   59,   53,   51,   51,   38,   51,   51,   51,
       51,   51,    5,   51,    6,   51,   51,   51,   51,   51,
       51,   12,   51,   51,   51,   51,   51,   51,   51,   21,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       45,   51,   51,   51,   60,   15,   51,   51,   51,   51,
       51,   51,    7,   51,   51,   51,   51,   51,   51,   51,
       16,   51,   17,   51,   19,   51,   51,   51,   51,   25,
       51,   51,   51,   51,   51,   51,   51,   33,   51,   51,
       51,   51,   51,   51,   51,   41,   51,   51,   51,   46,

       51,   51,   24,   51,   51,   51,   51,   51,   51,    9,
       51,   51,   11,   51,   51,   51,   51,   22,   51,   23,
       51,   26,   51,   51,   29,   51,   30,   51,   51,   51,
       34,   51,   35,   51,   51,   37,   51,   51,   51,   51,
       51,   51,   51,   51,   51,    4,   51,    8,   51,   10,
       51,   51,   14,   51,   51,   28,   51,   51,   51,   51,
       51,   40,   51,   51,   51,   47,   51,   51,    1,   51,
       51,   51,   51,   31,   51,   32,   51,   36,   51,   51,
       42,   51,   51,   43,   51,    3,   51,   13,   51,   20,
       51,   51,   44,   51,   51,   39,   51

    } ;

static yyconst short int yy_accept[308] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   13,   15,   18,
       21,   24,   26,   28,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   99,  100,  100,
      101,  101,  101,  101,  102,  102,  103,  104,  105,  105,
      105,  105,  106,  107,  108,  109,  110,  111,  112,  113,
      114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
      124,  125,  126,  127,  128,  129,  131,  132,  133,  134,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  151,  152,  153,  154,

      154,  154,  154,  155,  155,  156,  157,  158,  159,  160,
      161,  162,  164,  165,  166,  167,  168,  169,  170,  171,
      172,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      182,  183,  184,  186,  187,  188,  189,  190,  191,  192,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  204,  204,  205,  206,  207,  209,  210,  211,
      212,  213,  215,  217,  218,  219,  220,  221,  222,  224,
      225,  226,  227,  228,  229,  230,  232,  233,  234,  235,
      236,  237,  238,  239,  240,  241,  242,  243,  244,  245,
      246,  247,  248,  249,  250,  251,  253,  254,  255,  255,

      256,  256,  258,  259,  260,  261,  262,  263,  265,  266,
      267,  268,  269,  270,  271,  273,  275,  277,  278,  279,
      280,  282,  283,  284,  285,  286,  287,  288,  290,  291,
      292,  293,  294,  295,  296,  298,  299,  300,  302,  303,
      305,  306,  307,  308,  309,  310,  312,  313,  315,  316,
      317,  318,  320,  322,  324,  325,  327,  329,  330,  331,
      333,  335,  336,  338,  339,  340,  341,  342,  343,  344,
      345,  346,  348,  350,  352,  353,  355,  356,  358,  359,
      360,  361,  362,  364,  365,  366,  368,  369,  371,  372,
      373,  374,  376,  378,  380,  381,  383,  384,  386,  388,

      390,  392,  393,  395,  396,  398,  398
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    9,    9,
        9,    9,    9,    9,    9,   10,   10,   11,    1,   12,
        1,   13,    1,    1,   14,   15,   16,   16,   17,   18,
       19,   19,   19,   19,   19,   20,   19,   19,   21,   19,
       19,   22,   23,   24,   25,   26,   19,   27,   19,   19,
        1,   28,    1,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   19,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    4,    4,
        1,    1,    1,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    5,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5
    } ;

static yyconst short int yy_base[313] =
    {   0,
        0,    0,  402,  403,   52,   54,   54,  373,   75,  109,
       52,  389,  387,  385,    0,  383,  365,  373,  364,   32,
      350,   38,   30,   24,   58,  350,  348,  347,  359,   57,
       21,   60,   63,   19,  346,   48,   73,   99,   75,  403,
      384,  381,  119,    0,  123,  403,    0,  130,  141,  146,
        0,  159,  403,  403,  403,    0,  365,  345,  358,  342,
      334,  327,  331,  335,  330,  346,  333,  327,  338,  323,
      322,  338,  337,  316,  324,   65,  324,  332,  316,  315,
      328,  313,  322,  328,  320,  327,  311,  312,  308,  309,
      314,  321,  306,   83,  309,  310,  310,  298,  403,  136,

        0,  164,  169,  172,  176,    0,  322,  310,  326,  293,
      293,    0,  294,  299,  304,  291,   75,  288,  305,  303,
      292,  298,  283,  296,  299,  279,  293,  290,  276,  286,
      289,  271,    0,  271,  280,  272,  285,  268,  270,  104,
      271,  266,  271,  278,  268,  272,  260,  275,  277,  260,
      403,  154,  300,  403,  287,  271,    0,  268,  255,  262,
      265,    0,    0,  250,  263,  253,  246,  254,    0,  249,
      249,  258,  242,  241,  242,    0,  247,  236,  237,  254,
      253,  244,  247,  237,  245,  230,  235,  244,  232,  242,
      241,  239,  229,  234,  235,    0,  222,  229,  261,  403,

      260,    0,  216,  248,  232,  230,  230,    0,  207,  217,
      217,  222,  207,  208,    0,    0,    0,  218,  218,  217,
        0,  197,  201,  216,  200,  204,  203,    0,  208,  195,
      196,  204,  210,  205,    0,  196,  189,    0,  194,    0,
      205,  202,  184,  190,  183,    0,  175,    0,  177,  161,
      183,    0,    0,    0,  178,    0,    0,  170,  176,    0,
        0,  159,    0,  158,  170,  169,  149,  165,  153,  151,
      150,    0,    0,    0,  154,    0,  163,    0,  139,  157,
      143,  158,    0,  150,  126,    0,  131,    0,  126,  115,
      101,    0,    0,    0,  103,    0,   91,    0,    0,    0,

        0,   67,    0,   70,    0,  403,  216,  221,  223,   73,
       67,  226
    } ;

static yyconst short int yy_def[313] =
    {   0,
      306,    1,  306,  306,  306,  306,  307,  308,  306,  306,
      306,  306,  306,  306,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  306,  307,  306,
      307,  306,  306,    9,  306,  306,    9,  306,  306,  306,
      310,  306,  306,  306,  306,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  306,  306,

      311,  306,  306,  306,  306,  310,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      306,  306,  312,  306,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  306,  306,

      306,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,    0,  306,  306,  306,  306,
      306,  306
    } ;

static yyconst short int yy_nxt[457] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   11,
       12,   13,   14,   15,   15,   15,   15,   16,   15,   15,
       17,   15,   15,   18,   15,   19,   15,    4,    4,   20,
       21,   22,   23,   24,   25,   15,   15,   26,   15,   27,
       28,   29,   30,   31,   15,   32,   33,   34,   35,   36,
       37,   15,   15,   38,   38,   38,   38,   40,   47,   52,
       52,   52,   61,   69,   92,   71,   83,   65,   50,   84,
      153,   93,   70,   62,   66,   72,  106,   95,   40,   63,
       67,   41,   44,   44,   44,   50,   68,   73,   80,   85,
       96,   45,   46,   86,   46,   74,   87,   75,   81,   88,

       38,   38,   41,  305,   97,   82,  304,  126,   45,   46,
       89,   90,  127,   91,   46,   47,   48,   48,   49,   98,
      145,  164,  165,   99,  303,   50,  100,  100,  102,  146,
      103,  103,  103,  302,  301,   51,   47,   48,   48,   49,
      151,  187,   50,  152,  152,  101,   50,   47,   49,   49,
       49,  104,  188,  105,  105,  105,  300,   50,  151,  299,
       51,  199,  199,   50,  298,   47,   52,   52,   52,  297,
      101,  103,  103,  103,   50,   50,  103,  103,  103,  105,
      105,  105,  296,  105,  105,  105,   46,  295,   46,  294,
      293,  292,   50,  154,  291,  154,  290,  289,  288,  287,

      286,  285,  284,   46,  283,  282,  281,  280,   46,  279,
      154,  278,  277,  276,  275,  154,   39,   39,   39,   39,
       39,   42,  274,   42,   42,   42,   56,   56,  201,  201,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  200,  151,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,

      205,  204,  203,  202,  200,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  150,  149,  148,  147,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,   99,  306,   94,   79,   78,
       77,   76,   64,   60,   59,   58,   57,   55,   54,   53,

       43,  306,    3,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static yyconst short int yy_chk[457] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    6,    6,    7,   11,   11,
       11,   11,   20,   23,   34,   24,   31,   22,   11,   31,
      311,   34,   23,   20,   22,   24,  310,   36,   39,   20,
       22,    7,    9,    9,    9,   11,   22,   25,   30,   32,
       36,    9,    9,   32,    9,   25,   33,   25,   30,   33,

       38,   38,   39,  304,   37,   30,  302,   76,    9,    9,
       33,   33,   76,   33,    9,   10,   10,   10,   10,   37,
       94,  117,  117,   43,  297,   10,   43,   43,   45,   94,
       45,   45,   45,  295,  291,   10,   48,   48,   48,   48,
      100,  140,   10,  100,  100,   43,   48,   49,   49,   49,
       49,   50,  140,   50,   50,   50,  290,   49,  152,  289,
       10,  152,  152,   48,  287,   52,   52,   52,   52,  285,
       43,  102,  102,  102,   49,   52,  103,  103,  103,  104,
      104,  104,  284,  105,  105,  105,  103,  282,  103,  281,
      280,  279,   52,  105,  277,  105,  275,  271,  270,  269,

      268,  267,  266,  103,  265,  264,  262,  259,  103,  258,
      105,  255,  251,  250,  249,  105,  307,  307,  307,  307,
      307,  308,  247,  308,  308,  308,  309,  309,  312,  312,
      245,  244,  243,  242,  241,  239,  237,  236,  234,  233,
      232,  231,  230,  229,  227,  226,  225,  224,  223,  222,
      220,  219,  218,  214,  213,  212,  211,  210,  209,  207,
      206,  205,  204,  203,  201,  199,  198,  197,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  175,  174,  173,
      172,  171,  170,  168,  167,  166,  165,  164,  161,  160,

      159,  158,  156,  155,  153,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  139,  138,  137,  136,  135,
      134,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  116,  115,  114,  113,
      111,  110,  109,  108,  107,   98,   97,   96,   95,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   77,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,
       61,   60,   59,   58,   57,   42,   41,   35,   29,   28,
       27,   26,   21,   19,   18,   17,   16,   14,   13,   12,

        8,    3,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "./idl-g.ll"
#define INITIAL 0
#line 2 "./idl-g.ll"
#include <stdlib.h>
#include <stdio.h>

#include "y.tab.h"

static double  idl_atof(char *);
static long    idl_atoi(char *, long);
static unsigned char idl_escape_reader (char *str);
#line 650 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 12 "./idl-g.ll"


#line 804 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 403 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 14 "./idl-g.ll"
return ABSTRACT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "./idl-g.ll"
return ANY;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "./idl-g.ll"
return ATTRIBUTE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "./idl-g.ll"
return BOOLEAN;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "./idl-g.ll"
return CASE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "./idl-g.ll"
return CHAR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "./idl-g.ll"
return CONST;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "./idl-g.ll"
return CONTEXT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "./idl-g.ll"
return CUSTOM;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "./idl-g.ll"
return DEFAULT;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "./idl-g.ll"
return DOUBLE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "./idl-g.ll"
return ENUM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "./idl-g.ll"
return EXCEPTION;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "./idl-g.ll"
return FACTORY;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "./idl-g.ll"
return FALSE_TOKEN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "./idl-g.ll"
return FIXED;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "./idl-g.ll"
return FLOAT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "./idl-g.ll"
return IN;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "./idl-g.ll"
return INOUT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "./idl-g.ll"
return INTERFACE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "./idl-g.ll"
return LONG;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "./idl-g.ll"
return MODULE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "./idl-g.ll"
return NATIVE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "./idl-g.ll"
return OBJECT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "./idl-g.ll"
return OCTET;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "./idl-g.ll"
return ONEWAY;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "./idl-g.ll"
return OUT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "./idl-g.ll"
return PRIVATE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "./idl-g.ll"
return PUBLIC;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "./idl-g.ll"
return RAISES;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "./idl-g.ll"
return READONLY;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "./idl-g.ll"
return SEQUENCE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "./idl-g.ll"
return SHORT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "./idl-g.ll"
return STRING;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "./idl-g.ll"
return STRUCT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "./idl-g.ll"
return SUPPORTS;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "./idl-g.ll"
return SWITCH;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "./idl-g.ll"
return TRUE_TOKEN;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "./idl-g.ll"
return TRANCATABLE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "./idl-g.ll"
return TYPEDEF;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "./idl-g.ll"
return UNION;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "./idl-g.ll"
return UNSIGNED;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "./idl-g.ll"
return VALUEBASE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "./idl-g.ll"
return VALUETYPE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "./idl-g.ll"
return VOID;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "./idl-g.ll"
return WCHAR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "./idl-g.ll"
return WSTRING;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 62 "./idl-g.ll"
return LEFT_SHIFT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "./idl-g.ll"
return RIGHT_SHIFT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 66 "./idl-g.ll"
{
                 yylval.strval = "::";
                 return SCOPE_DELIMITOR;
               }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "./idl-g.ll"
{
                 char *z = (char *) malloc (strlen (yytext) + 1);
                 strcpy (z, yytext);
                 yylval.strval = z;
                 
                 return IDENTIFIER;
               }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "./idl-g.ll"
{
                 yylval.dval = idl_atof (yytext);
                 
                 printf ("Flat: [%f]\n", yylval.dval);
                 return FLOATING_PT_LITERAL;
               }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "./idl-g.ll"
{
                 yylval.dval = idl_atof (yytext);
                 return FLOATING_PT_LITERAL;
               }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "./idl-g.ll"
{
                 yylval.ival = idl_atoi (yytext, 10);
                 return INTEGER_LITERAL;
               }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "./idl-g.ll"
{
                 yylval.ival = idl_atoi (yytext, 16);
                 return INTEGER_LITERAL;
               }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "./idl-g.ll"
{
                 yylval.ival = idl_atoi (yytext, 8);
                 return INTEGER_LITERAL;
               }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "./idl-g.ll"
{
                 char *z = (char *) malloc (strlen (yytext) + 1);
                 strcpy (z, yytext);
                 yylval.strval = z;
                 return STRING_LITERAL;
               }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 113 "./idl-g.ll"
{
                 yylval.cval = yytext[1];
                 return CHARACTER_LITERAL;
               }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 118 "./idl-g.ll"
{
                 // octal character constant
                 yylval.cval = idl_escape_reader(yytext + 1);
                 return CHARACTER_LITERAL;
               }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "./idl-g.ll"
{
                 // hex character constant
                 yylval.cval = idl_escape_reader(yytext + 1);
                 return CHARACTER_LITERAL;
               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "./idl-g.ll"
;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "./idl-g.ll"
return yytext[0];
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "./idl-g.ll"
ECHO;
	YY_BREAK
#line 1252 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 306);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 134 "./idl-g.ll"


/*
 * idl_atoi - Convert a string of digits into an integer according to base b
 */
static long idl_atoi(char *s, long b)
{
       long    r = 0;
       long    negative = 0;

       if (*s == '-') {
         negative = 1;
         s++;
       }
       if (b == 8 && *s == '0')
         s++;
       else if (b == 16 && *s == '0' && (*(s + 1) == 'x' || *(s + 1) == 'X'))
         s += 2;

       for (; *s; s++)
         if (*s <= '9' && *s >= '0')
           r = (r * b) + (*s - '0');
         else if (b > 10 && *s <= 'f' && *s >= 'a')
           r = (r * b) + (*s - 'a' + 10);
         else if (b > 10 && *s <= 'F' && *s >= 'A')
           r = (r * b) + (*s - 'A' + 10);
         else
           break;

       if (negative)
         r *= -1;

       return r;
}

/*
 * Convert a string to a float; atof doesn't seem to work, always.
 */
static double idl_atof(char *s)
{

       double  d = 0.0;

       double  e, k;
       long    neg = 0, negexp = 0;

       if (*s == '-') {
         neg = 1;
         s++;
       }
       while (*s >= '0' && *s <= '9') {
               d = (d * 10) + *s - '0';
               s++;
       }
       if (*s == '.') {
               s++;
               e = 10;
               while (*s >= '0' && *s <= '9') {
                       d += (*s - '0') / (e * 1.0);
                       e *= 10;
                       s++;
               }
       }
       if (*s == 'e' || *s == 'E') {
               s++;
               if (*s == '-') {
                       negexp = 1;
                       s++;
               } else if (*s == '+')
                       s++;
               e = 0;
               while (*s >= '0' && *s <= '9') {
                       e = (e * 10) + *s - '0';
                       s++;
               }
               if (e > 0) {
                       for (k = 1; e > 0; k *= 10, e--);
                       if (negexp)
                               d /= k;
                       else
                               d *= k;
               }
       }

       if (neg) d *= -1.0;

       return d;
}

/*
 * Convert (some) escaped characters into their ascii values
 */
static unsigned char idl_escape_reader (char *str)
{
    if (str[0] != '\\') {
       return str[0];
    }

    switch (str[1]) {
      case 'n':
       return '\n';
      case 't':
       return '\t';
      case 'v':
       return '\v';
      case 'b':
       return '\b';
      case 'r':
       return '\r';
      case 'f':
       return '\f';
      case 'a':
       return '\a';
      case '\\':
       return '\\';
      case '\?':
       return '?';
      case '\'':
       return '\'';
      case '"':
       return '"';
      case 'x':
       {
           // hex value
           int i;
           char save, out;

           for (i = 2; str[i] != '\0' && isxdigit(str[i]); i++)
           {
               continue;
           }

           save = str[i];
           str[i] = '\0';
           out = (char)idl_atoi(&str[2], 16);
           str[i] = save;
           return out;
       }
       break;
      default:
       // check for octal value
       if (str[1] >= '0' && str[1] <= '7')
       {
           int i;
           char save, out;

           for (i = 1; str[i] >= '0' && str[i] <= '7'; i++)
           {
               continue;
           }

           save = str[i];
           str[i] = '\0';
           out = (char)idl_atoi(&str[1], 8);
           str[i] = save;
           return out;
       }
       else
       {
         return str[1] - 'a';
       }

       break;
    }

    return 0;
}
