/* Automatically generated by autochaos 0.2.0. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "tetris"
#define PACKAGE_VERSION "0.0.1"

#include <console/console.h>
#include <file/file.h>
#include <ipc/ipc.h>
#include <log/log.h>
#include <memory/memory.h>
#include <pci/pci.h>
#include <random/random.h>
#include <string/string.h>
#include <time/time.h>
#include <system/system.h>
#include <video/video.h>

#include <storm/storm.h>
#endif /* !__CONFIG_H__ */