# $Id: makefile.template,v 1.1 2001/02/10 22:58:45 jojo Exp $
# Local rules.

stormG2: current-arch

# FIXME: Make this detect the architecture in some way.

current-arch:
	ln -sf ia32 current-arch

clean-local:
	rm -f current-arch
