interface block
{
    typedef sequence<octet> block_data_t;

    unsigned long read (
        in  unsigned long long offset,
        in  unsigned long length,
        out block_data_t data
    );

    unsigned long write (
        in  unsigned long long offset,
        in  unsigned long length,
        in  block_data_t data
    );
};
