interface event_observer
{
    typedef sequence<octet> event_data_t;

    return_t read (
        out event_data_t data
    );

    return_t peek (
        out event_data_t data
    );
};
