/* Automatically generated by autochaos 0.2.0. Not intended to be
   hand edited. */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE_NAME "event"
#define PACKAGE_VERSION "0.0.1"

#include <system/system.h>
#include <memory/memory.h>

#endif /* !__CONFIG_H__ */