.TH "cpu_register_cr2_t" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpu_register_cr2_t \- Structure of system register CR2.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <cr2.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBpage_fault_linear_address\fP"
.br
.RI "\fIPage-fault linear address (the linear address that caused a page fault). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure of system register CR2. 

Contains the page-fault linear address (the linear address that caused a page fault). 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
