.TH "cr3.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cr3.h \- Descriptions of CR3 register.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcpu_register_cr3_t\fP"
.br
.RI "\fIStructure of system register CR3. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCPU_CR3_PWT\fP   (\fBBIT_VALUE\fP (3))"
.br
.RI "\fIPWT Page-level Writes Transparent (bit 3 of CR3). \fP"
.ti -1c
.RI "#define \fBCPU_CR3_PCD\fP   (\fBBIT_VALUE\fP (4))"
.br
.RI "\fIPCD Page-level Cache Disable (bit 4 of CR3). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Descriptions of CR3 register. 

\fBAuthor:\fP
.RS 4
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
2002-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
