.TH "cr4.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cr4.h \- Descriptions of CR4 register.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcpu_register_cr4_t\fP"
.br
.RI "\fIStructure of system register CR4. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Descriptions of CR4 register. 

\fBAuthor:\fP
.RS 4
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
2002-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
