.TH "descriptor.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
descriptor.h \- The descriptor structure.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdescriptor_t\fP"
.br
.RI "\fIA descriptor. \fP"
.ti -1c
.RI "struct \fBgate_descriptor_t\fP"
.br
.RI "\fIA gate descriptor. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDESCRIPTOR_NULL\fP   0ULL"
.br
.RI "\fIEmpty descriptor. \fP"
.ti -1c
.RI "#define \fBDESCRIPTOR_CODE\fP(base, limit, granularity, dpl, present, digit)"
.br
.RI "\fIDescriptor of code segment. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBprivilege_level_t\fP "
.br
.ti -1c
.RI "enum \fBdescriptor_type_t\fP { \fBDESCRIPTOR_TYPE_TASK_GATE_32\fP =  5, \fBDESCRIPTOR_TYPE_TSS\fP =  9, \fBDESCRIPTOR_TYPE_CALL_GATE\fP =  12, \fBDESCRIPTOR_TYPE_INTERRUPT_GATE_32\fP =  14, \fBDESCRIPTOR_TYPE_TRAP_GATE_32\fP =  15 }"
.br
.RI "\fIDescriptor types. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The descriptor structure. 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org> 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.7 
.RE
.PP
\fBDate:\fP
.RS 4
1998-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
