.TH "error_codes.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_codes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsegment_error_t\fP"
.br
.RI "\fIError code pushed onto the stack for segment exceptions. \fP"
.ti -1c
.RI "struct \fBpage_error_t\fP"
.br
.RI "\fIError code pushed onto the stack for page exceptions. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSEGMENT_ERROR_EXT\fP   \fBBIT_VALUE\fP (0)"
.br
.ti -1c
.RI "#define \fBSEGMENT_ERROR_IDT\fP   \fBBIT_VALUE\fP (1)"
.br
.ti -1c
.RI "#define \fBSEGMENT_ERROR_TI\fP   \fBBIT_VALUE\fP (2)"
.br
.ti -1c
.RI "#define \fBSEGMENT_ERROR_SELECTOR_INDEX\fP(x)"
.br
.ti -1c
.RI "#define \fBPAGE_ERROR_P\fP   \fBBIT_VALUE\fP (0)"
.br
.ti -1c
.RI "#define \fBPAGE_ERROR_W_R\fP   \fBBIT_VALUE\fP (1)"
.br
.ti -1c
.RI "#define \fBPAGE_ERROR_U_S\fP   \fBBIT_VALUE\fP (2)"
.br
.ti -1c
.RI "#define \fBPAGE_ERROR_RSVD\fP   \fBBIT_VALUE\fP (3)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
