.TH "exceptions.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.h \- Exception stuff.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Exceptions/classes.h'\fP
.br
\fC#include 'Exceptions/error_codes.h'\fP
.br
\fC#include 'Exceptions/codes.h'\fP
.br

.SH "Detailed Description"
.PP 
Exception stuff. 

\fBAuthor:\fP
.RS 4
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
1999-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
