.TH "fpu_tag_word_t" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fpu_tag_word_t \- FPU Tag Word.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <fpu.h>\fP
.PP
.SH "Detailed Description"
.PP 
FPU Tag Word. 

The 16-bit tag word indicates the contents of each the 8 registers in the FPU data-register stack (one 2-bit tag per register). The tag codes indicate whether a register contains a valid number, zero, or a special floating-point number (NaN, infinity, denormal, or unsupported format), or whether it is empty. The FPU tag word is cached in the FPU in the FPU tag word register. When the FPU is initialized with either an FINIT/FNINIT or FSAVE/FNSAVE instruction, the FPU tag word is set to FFFFH, which marks all the FPU data registers as empty. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
