.TH "fpu_state_t" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fpu_state_t \- Protected Mode FPU State Image in Memory, 32-Bit Format.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <fpu.h>\fP
.PP
.SH "Detailed Description"
.PP 
Protected Mode FPU State Image in Memory, 32-Bit Format. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
