.TH "gate_descriptor_t" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gate_descriptor_t \- A gate descriptor.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <descriptor.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBoffset_lo\fP"
.br
.RI "\fILow 16 bits of offset. \fP"
.ti -1c
.RI "\fBuint16_t\fP \fBsegment_selector\fP"
.br
.RI "\fISegment selector. \fP"
.ti -1c
.RI "\fBuint8_t\fP \fBparams\fP: 5"
.br
.RI "\fIZero if not type == 12. \fP"
.ti -1c
.RI "\fBuint8_t\fP \fBdpl\fP: 2"
.br
.RI "\fIDescriptor privilege level. \fP"
.ti -1c
.RI "\fBuint8_t\fP \fBpresent\fP: 1"
.br
.RI "\fIIf zero, this descriptor isn't used. \fP"
.ti -1c
.RI "\fBuint16_t\fP \fBoffset_hi\fP"
.br
.RI "\fIHigh 16 bits of offset. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A gate descriptor. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
