.TH "gdt.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdt.h \- GDT description and functions.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdescriptor_t\fP \fBgdt\fP []"
.br
.RI "\fIThe GDT (Global Descriptors Table). \fP"
.in -1c
.SH "Detailed Description"
.PP 
GDT description and functions. 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org> 
.PP
Henrik Hallin <hal@chaosdev.org> 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.12 
.RE
.PP
\fBDate:\fP
.RS 4
1998-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
