.TH "IDT" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDT \- Interrupt Descriptors Table (IDT).  
More...
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdescriptor_t\fP \fBidt\fP []"
.br
.RI "\fIThe IDT (Interrupt Descriptors Table). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interrupt Descriptors Table (IDT). 
