.TH "Exceptions" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exceptions \- Hardware exceptions in x86 architecture.  
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBException classifications\fP"
.br
.RI "\fIExceptions are classified as faults, traps, or aborts depending on the way they are reported and whether the instruction that caused the exception can be restarted with no loss of program or task continuity. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBException codes\fP"
.br
.ti -1c
.RI "\fBException error codes\fP"
.br
.RI "\fIError codes that pushed in stack then exception occured. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
Hardware exceptions in x86 architecture. 
