.TH "Paging" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Paging \- Paging in x86 architecture.  
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPages\fP"
.br
.RI "\fIPage in x86 architecture. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBPage directory\fP"
.br
.RI "\fIPage directories in x86 architecture. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBPage table\fP"
.br
.RI "\fIPage tables in x86 architecture. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
Paging in x86 architecture. 
