.TH "CR4 register" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CR4 register \- CR4 register.  
More...
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcpu_register_cr4_t\fP"
.br
.RI "\fIStructure of system register CR4. \fP"
.in -1c
.SH "Detailed Description"
.PP 
CR4 register. 
