.TH "Page flags" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Page flags \- Page flags.  
More...
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPAGE_PRESENT\fP   \fBBIT_VALUE\fP (0)"
.br
.RI "\fIIs the page present in memory? \fP"
.ti -1c
.RI "#define \fBPAGE_WRITABLE\fP   \fBBIT_VALUE\fP (1)"
.br
.RI "\fIIs the page writable? \fP"
.ti -1c
.RI "#define \fBPAGE_NON_PRIVILEGED\fP   \fBBIT_VALUE\fP (2)"
.br
.RI "\fICan the page be accessed from nonprivileged (ring 3) code? \fP"
.ti -1c
.RI "#define \fBPAGE_WRITE_THROUGH\fP   \fBBIT_VALUE\fP (3)"
.br
.RI "\fIIs write-through cache enabled for the page? \fP"
.ti -1c
.RI "#define \fBPAGE_CACHE_DISABLE\fP   \fBBIT_VALUE\fP (4)"
.br
.RI "\fIIs caching completely disabled for this page? \fP"
.ti -1c
.RI "#define \fBPAGE_GLOBAL\fP   \fBBIT_VALUE\fP (8)"
.br
.RI "\fIIs this a global page, shared between all page directories? \fP"
.in -1c
.SH "Detailed Description"
.PP 
Page flags. 
.SH "Define Documentation"
.PP 
.SS "#define PAGE_CACHE_DISABLE   \fBBIT_VALUE\fP (4)"
.PP
Is caching completely disabled for this page? This flag is neccessary to use when mapping I/O devices. 
