.TH "Page table" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Page table \- Page tables in x86 architecture.  
More...
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpage_table_t\fP"
.br
.RI "\fIA page table entry (PTE). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Page tables in x86 architecture. 
