.TH "Pages" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pages \- Page in x86 architecture.  
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPage flags\fP"
.br
.RI "\fIPage flags. \fP"
.PP

.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPAGE_SIZE\fP   (0x1000U)"
.br
.RI "\fIThe size of a physical page. \fP"
.ti -1c
.RI "#define \fBPAGE_BITS\fP   12"
.br
.RI "\fIThe number of bits of a page. \fP"
.ti -1c
.RI "#define \fBPAGE_ADDRESS\fP(x)   ((x) << PAGE_BITS)"
.br
.RI "\fIThe address of page. \fP"
.ti -1c
.RI "#define \fBPAGE_ALIGN_DOWN\fP(x)   ((void *) (((\fBuint32_t\fP) (x)) & 0xFFFFF000))"
.br
.RI "\fIRound address to nearest page. \fP"
.ti -1c
.RI "#define \fBPAGE_NUMBER\fP(x)   ((\fBpage_number_t\fP) (((\fBaddress_t\fP) (x)) >> PAGE_BITS))"
.br
.RI "\fIThe page number of an address. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBuint32_t\fP \fBpage_number_t\fP"
.br
.RI "\fIA page number. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Page in x86 architecture. 
