.TH "Page directory" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Page directory \- Page directories in x86 architecture.  
More...
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpage_directory_4mb_t\fP"
.br
.RI "\fIA page directory entry (PDE) when using 4MiB pages. \fP"
.ti -1c
.RI "struct \fBpage_directory_t\fP"
.br
.RI "\fIA page directory entry (PDE). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Page directories in x86 architecture. 
