.TH "System registers" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System registers \- System registers in x86 architecture.  
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCR0 register\fP"
.br
.RI "\fICR0 register. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBCR2 register\fP"
.br
.RI "\fICR2 register. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBCR3 register\fP"
.br
.RI "\fICR3 register. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBCR4 register\fP"
.br
.RI "\fICR4 register. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
System registers in x86 architecture. 
