.TH "CR2 register" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CR2 register \- CR2 register.  
More...
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcpu_register_cr2_t\fP"
.br
.RI "\fIStructure of system register CR2. \fP"
.in -1c
.SH "Detailed Description"
.PP 
CR2 register. 
