.TH "Segmentation" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Segmentation \- Segmentation in x86 architecture.  
More...
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSegment descriptors\fP"
.br
.RI "\fISegment descriptors in x86 architecture. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBGDT\fP"
.br
.RI "\fIGlobal Descriptors Table (GDT). \fP"
.PP
.in +1c

.ti -1c
.RI "\fBIDT\fP"
.br
.RI "\fIInterrupt Descriptors Table (IDT). \fP"
.PP
.in +1c

.ti -1c
.RI "\fBSegment selectors\fP"
.br
.RI "\fISegment selectors in x86 architecture. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBTSS\fP"
.br
.RI "\fITSS (Task State Segment). \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
Segmentation in x86 architecture. 
