.TH "Exception error codes" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exception error codes \- Error codes that pushed in stack then exception occured.  
More...
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsegment_error_t\fP"
.br
.RI "\fIError code pushed onto the stack for segment exceptions. \fP"
.ti -1c
.RI "struct \fBpage_error_t\fP"
.br
.RI "\fIError code pushed onto the stack for page exceptions. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Error codes that pushed in stack then exception occured. 
