.TH "FPU round flags" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FPU round flags \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFPU_ROUND_TO_NEAREST\fP   00B"
.br
.RI "\fIRound to nearest (even). \fP"
.ti -1c
.RI "#define \fBFPU_ROUND_DOWN\fP   01B"
.br
.RI "\fIRound down. \fP"
.ti -1c
.RI "#define \fBFPU_ROUND_UP\fP   10B"
.br
.RI "\fIRound up. \fP"
.ti -1c
.RI "#define \fBFPU_ROUND_TOWARD\fP   11B"
.br
.RI "\fIRound toward zero (Truncate). \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FPU_ROUND_TO_NEAREST   00B"
.PP
Round to nearest (even). Rounded result is the closest to the infinitely precise result. If two values are equally close, the result is the even value (that is, the one with the least-significant bit of zero). 
.SS "#define FPU_ROUND_DOWN   01B"
.PP
Round down. Rounded result is close to but no greater than the infinitely precise result. 
.SS "#define FPU_ROUND_UP   10B"
.PP
Round up. Rounded result is close to but no less than the infinitely precise result. 
.SS "#define FPU_ROUND_TOWARD   11B"
.PP
Round toward zero (Truncate). Rounded result is close to but no greater in absolute value than the infinitely precise result. 
