.TH "Hardcoded vendors strings" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardcoded vendors strings \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBVENDOR_UNKNOWN_STRING\fP   '------------'"
.br
.RI "\fIHardcoded string of unknown CPU's vendor. \fP"
.ti -1c
.RI "#define \fBVENDOR_AMD_STRING\fP   'AuthenticAMD'"
.br
.RI "\fIHardcoded string of AMD. \fP"
.ti -1c
.RI "#define \fBVENDOR_INTEL_STRING\fP   'GenuineIntel'"
.br
.RI "\fIHardcoded string of Intel. \fP"
.ti -1c
.RI "#define \fBVENDOR_CYRIX_STRING\fP   'CyrixInstead'"
.br
.RI "\fIHardcoded string of Cyrix. \fP"
.ti -1c
.RI "#define \fBVENDOR_CENTAUR_STRING\fP   'CentaurHauls'"
.br
.RI "\fIHardcoded string of Centaur. \fP"
.ti -1c
.RI "#define \fBVENDOR_UMC_STRING\fP   'UMC UMC UMC '"
.br
.RI "\fIHardcoded string of UMC. \fP"
.ti -1c
.RI "#define \fBVENDOR_NEXGEN_STRING\fP   'NexGenDriven'"
.br
.RI "\fIHardcoded string of NexGen. \fP"
.ti -1c
.RI "#define \fBVENDOR_RISETECHNOLOGY_STRING\fP   'RiseRiseRise'"
.br
.RI "\fIHardcoded string of Rise Technology. \fP"
.ti -1c
.RI "#define \fBVENDOR_TRANSMETA_STRING\fP   'GenuineTMx86'"
.br
.RI "\fIHardcoded string of Transmeta. \fP"
.in -1c
