.TH "GDT" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GDT \- Global Descriptors Table (GDT).  
More...
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdescriptor_t\fP \fBgdt\fP []"
.br
.RI "\fIThe GDT (Global Descriptors Table). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Global Descriptors Table (GDT). 
