.TH "limits.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
limits.h \- Function prototypes for IDT functions.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGDT_ENTRIES\fP   (256)"
.br
.RI "\fIThe number of max entries in the GDT. \fP"
.ti -1c
.RI "#define \fBGDT_SIZE\fP   (GDT_ENTRIES * sizeof (\fBdescriptor_t\fP))"
.br
.RI "\fIThe size of the GDT. \fP"
.ti -1c
.RI "#define \fBIDT_ENTRIES\fP   (256)"
.br
.RI "\fIThe number of entries in the IDT. \fP"
.ti -1c
.RI "#define \fBIDT_SIZE\fP   (IDT_ENTRIES * sizeof (\fBdescriptor_t\fP))"
.br
.RI "\fIThe size of the IDT. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Function prototypes for IDT functions. 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org> 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
1998-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
