.TH "idt.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idt.h \- Function prototypes for IDT functions.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdescriptor_t\fP \fBidt\fP []"
.br
.RI "\fIThe IDT (Interrupt Descriptors Table). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Function prototypes for IDT functions. 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org> 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.8 
.RE
.PP
\fBDate:\fP
.RS 4
1998-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
