.TH "limits.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
limits.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBKERNEL_STACK_SIZE\fP   (4 * \fBKIB\fP)"
.br
.RI "\fISize of some regions. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define KERNEL_STACK_SIZE   (4 * \fBKIB\fP)"
.PP
Size of some regions. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
