.TH "segmentation.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
segmentation.h \- Segment description and functions.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Segmentation/descriptor.h'\fP
.br
\fC#include 'Segmentation/selectors.h'\fP
.br
\fC#include 'Segmentation/gdt.h'\fP
.br
\fC#include 'Segmentation/idt'\fP
.br
\fC#include 'Segmentation/tss.h'\fP
.br

.SH "Detailed Description"
.PP 
Segment description and functions. 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org> 
.PP
Henrik Hallin <hal@chaosdev.org> 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
2002-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
