.TH "selectors.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
selectors.h \- Segment selectors description.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBselector_t\fP"
.br
.RI "\fIA segment selector. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSELECTOR\fP(index, ldt, rpl)   (((index) << 3) | ((ldt) << 2) | (rpl))"
.br
.RI "\fISegment selector. \fP"
.ti -1c
.RI "#define \fBSELECTOR_TSS1\fP   (SELECTOR (DESCRIPTOR_INDEX_TSS1, 0, PRIVILEGE_LEVEL_SYSTEM))"
.br
.RI "\fIThe first TSS selector. \fP"
.ti -1c
.RI "#define \fBSELECTOR_TSS2\fP   (SELECTOR (DESCRIPTOR_INDEX_TSS2, 0, PRIVILEGE_LEVEL_SYSTEM))"
.br
.RI "\fIThe second TSS selector. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Segment selectors description. 

\fBAuthor:\fP
.RS 4
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
0.1 
.RE
.PP
\fBDate:\fP
.RS 4
2002-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
