.TH "system_registers.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system_registers.h \- Descriptions of most significal system registers.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Descriptions of most significal system registers. 

\fBAuthor:\fP
.RS 4
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
0.1 
.RE
.PP
\fBDate:\fP
.RS 4
2002-2004
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
