.TH "tss.h" 3 "29 Jul 2004" "Systemenviroment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tss.h \- A structure for holding an Intel TSS (Task State Segment).  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtss_t\fP"
.br
.RI "\fIA TSS (Task State Segment). \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTSS_NEW_EFLAGS\fP"
.br
.RI "\fIThe CPU flags to use when setting up a new TSS. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A structure for holding an Intel TSS (Task State Segment). 

\fBAuthor:\fP
.RS 4
Per Lundberg <per@chaosdev.org>, 
.PP
Vladimir Sorokin 
.RE
.PP
\fBVersion:\fP
.RS 4
1.4 
.RE
.PP
\fBDate:\fP
.RS 4
1998-2002
.RE
.PP
TSS:es are used for doing task switching. All the register values of a task is stored in the TSS.
.SH "Author"
.PP 
Generated automatically by Doxygen for Systemenviroment from the source code.
